### ISSUE TITLE
Accumulo/HBase HDFS classloading fails

### ISSUE THREAD

**Issue by elahrvivaz** [locationtech/geomesa#7116]
Accumulo/HBase HDFS classloading fails

The version of indriya we (through geotools) are using is affected by [https://github.com/unitsofmeasurement/indriya/issues/383](https://github.com/unitsofmeasurement/indriya/issues/383) . Unfortunately it seems that upgrading to the fixed version of that library (2.2) doesn’t work with geotools and/or the si.uom libraries used by geotools.
 
The current work-around is to put the geomesa jar into accumulo/lib on each tserver, or use the 3.5 geomesa-accumulo-distributed-runtime jar, which works with 4.0 as well.
 
The tservers fail with errors like:
  java.lang.NoClassDefFoundError: Could not initialize class org.locationtech.geomesa.utils.geotools.package$ at org.locationtech.geomesa.utils.geotools.sft.SimpleFeatureSpec$GeomAttributeSpec.builderHook(SimpleFeatureSpec.scala:179)   java.lang.NoClassDefFoundError: Could not initialize class tech.units.indriya.unit.Units  
Trying to upgrade indriya results in unit test failures:
  java.lang.NoClassDefFoundError: Could not initialize class si.uom.NonSI at org.geotools.referencing.datum.DefaultPrimeMeridian.(DefaultPrimeMeridian.java:46) at org.geotools.referencing.datum.DefaultGeodeticDatum.(DefaultGeodeticDatum.java:72) at org.geotools.referencing.crs.DefaultGeographicCRS.(DefaultGeographicCRS.java:91) at org.locationtech.geomesa.utils.geotools.package$.liftedTree1$1(package.scala:29) at org.locationtech.geomesa.utils.geotools.package$.(package.scala:29) at org.locationtech.geomesa.utils.geotools.package$.(package.scala) at org.locationtech.geomesa.utils.geotools.sft.SimpleFeatureSpec$GeomAttributeSpec.builderHook(SimpleFeatureSpec.scala:188)

---

**Original JIRA Issue:** https://geomesa.atlassian.net/browse/GEOMESA-3292

**Key:** GEOMESA-3292
**Type:** Bug
**Priority:** Major
**Status:** Done
**Resolution:** Fixed
**Assignee:** Emilio Lahr-Vivaz
**Reporter:** Emilio Lahr-Vivaz
**Created:** Wed, 30 Aug 2023 10:38:03 -0400
**Updated:** Wed, 29 May 2024 08:27:30 -0400
**Resolved:** Mon, 26 Feb 2024 10:04:59 -0500
**Fix Version(s):** 5.0.0
**Affects Version(s):** 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4

---

**Comments:**

**557058:da7f6dfa-f0a1-468b-aec5-2cb61273feb5** (Thu, 31 Aug 2023 12:29:32 -0400):

Draft PR here: [https://github.com/locationtech/geomesa/pull/2992](https://github.com/locationtech/geomesa/pull/2992)

**557058:da7f6dfa-f0a1-468b-aec5-2cb61273feb5** (Wed, 17 Jan 2024 09:29:30 -0500):

The geotools upgrade in geomesa 5 seems like it’s compatible with the upgraded indriya jar, so we don’t need to add work-arounds.

**557058:da7f6dfa-f0a1-468b-aec5-2cb61273feb5** (Mon, 26 Feb 2024 10:04:59 -0500):

[https://github.com/locationtech/geomesa/commit/5b0ce87473268771702bb4026912bcde35e4edbc](https://github.com/locationtech/geomesa/commit/5b0ce87473268771702bb4026912bcde35e4edbc)

**557058:da7f6dfa-f0a1-468b-aec5-2cb61273feb5** (Wed, 29 May 2024 08:27:30 -0400):

Associated indriya bug: [https://github.com/unitsofmeasurement/indriya/issues/383](https://github.com/unitsofmeasurement/indriya/issues/383)
